name: core
description: Core utilities for CryptoFlow

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Network
  dio: ^5.3.0
  web_socket_channel: ^2.4.0
  connectivity_plus: ^5.0.0
  
  # Firebase
  cloud_firestore: ^5.4.0
  
  # Functional
  dartz: ^0.10.1
  equatable: ^2.0.5
  rxdart: ^0.27.7
  
  # Utils
  intl: ^0.18.0

