name: notifications
description: Push notifications for CryptoFlow

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Local packages
  core:
    path: ../core
  
  # Firebase
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  
  # Local Notifications
  flutter_local_notifications: ^20.0.0
  
  # State management
  flutter_bloc: ^9.1.1
  
  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # Storage
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  mocktail: ^1.0.0
  bloc_test: ^10.0.0
